[package]
edition = "2021"
name = "configs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.9.0"
serde = {version = "1.0", features = ["derive"]}

toml = "0.5"
